language: node_js
node_js:
- "14"

services:
- mongodb

install:
- npm install

env:
- APP_PORT=3000

before_script:
- nohup npm run start &
- sleep 10s

script:
- node_modules/.bin/newman run tests/volume.postman_collection.json -e tests/volume.postman_environment.json