language: node_js
node_js:
- "8.2.1"

services:
- mongodb

install:
- npm install

before_script:
- node --version
- npm --version
- node_modules/.bin/newman --version

script:
- node_modules/.bin/newman run tests/volume.postman_collection.json -e tests/volume.postman_environment.json