language: node_js
node_js:
- "14"

services:
- mongodb

install:
- npm install

env:
- APP_PORT=3000

before_script:
- nohup npm run start &
- sleep 15
- mongo volume --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'

script:
- npm run test