version: "3.6"

services:
  web:
    container_name: "volume"
    build: 
      context: .
      dockerfile: Dockerfile
    env_file: .dockerenvrc
    volumes: 
      - ~/MongoDB/data:/data/db
    ports:
      - "80:3000"
    links:
      - db
  db:
    container_name: "volume-db"
    image: mongo
    ports:
      - "27888:27017"