version: "3.6"

services:
  web:
    container_name: "volume"
    build: 
      context: .
      dockerfile: Dockerfile
    env_file: .dockerenvrc
    ports:
      - "80:3000"
    networks:
      - app-network
  
  db:
    container_name: "volume-db"
    image: mongo
    volumes: 
      - ~/MongoDB/data:/data/db
    ports:
      - "27888:27017"
    networks:
      - app-network
  
networks:
  app-network:
    driver: bridge